version: '3.8'
services:
  node:
    build:
      context: .
    env_file: ./.env
    depends_on:
      - db
    command: npm start
    links:
      - db
    volumes:
      - .:/app/
      - /app/node_modules
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local